### ISSUE TITLE
Remember toggle state

### ISSUE THREAD

**Issue by maevisnyctophilia** [azouaoui-med/pro-sidebar-template#1]
Hi there!

I have been messing with this wonderful sidebar and was wondering if there was a way to set it so that it remembers its' toggle state upon refresh. 

I don't know a whole lot about dissecting script and writing it, even if I can sort of use what's there enough to tweak understand. I can't seem to effectively modify and fit any codes involving cookies to the sidebar. I would love some help or a code I can plug in or replace. I really love this sidebar and don't want to have to wind up using something else. 

Thank you for any help.

**Comment by azouaoui-med** [comment]
Since the toggle state is dependent on the toggled class you can use local-storage to save the state 
```
 $("#toggle-sidebar").click(function () {
        $(".page-wrapper").toggleClass("toggled");
        if ($(".page-wrapper").hasClass("toggled")){
            localStorage.setItem("toggled", "true");
        }else{
            localStorage.setItem("toggled", "false");
        }
    });
```

And then you can check the value of the created local-storage when refreshing 

```
 if (localStorage.getItem("toggled") == "true"){
        $(".page-wrapper").addClass("toggled");
    }else if (localStorage.getItem("toggled") == "false"){
        $(".page-wrapper").removeClass("toggled");
    }
```

**Comment by azouaoui-med** [comment]
This worked fine for me, you should check for errors in your console
