### ISSUE TITLE
Dude you pinned the sidebar WHOOHOO

### ISSUE THREAD

**Issue by osc2nuke** [azouaoui-med/pro-sidebar-template#12]
This is not an issue at all.
There is just no other way to give you a compliment!

**Comment by osc2nuke** [comment]
You are very close to something that will and can be used wide abroad many applications.
For some it might look obvious to make such menu on them self.
But if make it right!!!
This menu has global usage capacity.

I have one suggestion.
The pin/toggle functionality, could also be implemented in the header nav.
There is in fact various ways, it could even be inside the menu itself. as hovering over does already open the menu.
Think of it!

Still great work and hard to find such a standalone bootstrap option.

**Comment by azouaoui-med** [comment]
Thank you very much, i really appreciate the feedback and i will make sure to improve it as much as i can, and i will take the suggestions you made into consideration

Thanks again :)
