### ISSUE TITLE
Multiple minor things

### ISSUE THREAD

**Issue by vizcay** [azouaoui-med/pro-sidebar-template#14]
Hi! I 've came across pro-sidebar a few weeks ago and decided to wrap it on a Ruby gem for Rails applications and release it. We found a number a minor issues while in the process.. do you want us to file those and send some pull requests?

For example an important one is that the js and css for the sidebar is somewhat mixed with the demo, so we had to extract it. Also, the SCSS is not all evenly formatted.

**Comment by azouaoui-med** [comment]
Hi! Thank you for your feedback..
I always try to improve the sidebar and make it easy to use, so i'm open to any suggestions that can improve it :)

**Comment by vizcay** [comment]
Hey, that sounds great. I will then close this issue and start sending merge requests or filing suggestions.
