### ISSUE TITLE
Bootstrap4 sticky-top navbar in page-content div container-fluid?

### ISSUE THREAD

**Issue by aa-delite** [azouaoui-med/pro-sidebar-template#24]
Hi! Thank you for amazing job you did!
Is it possible to make sticky-top navbar in page-content div container-fluid?

```
            <main class="page-content pt-0">
                <div id="overlay" class="overlay"></div>
                <div class="container-fluid p-0">
                    <nav class="navbar navbar-light sticky-top">
```
"sticky-top" doesn't work at all. "fixed-top" ignores sidebar and using full page width.

**Comment by xlievo** [comment]
I have the same problem!
