### ISSUE TITLE
Add Multilevel Dropdown

### ISSUE THREAD

**Issue by bharatribadiya** [azouaoui-med/pro-sidebar-template#27]
Please add multilevel drop down

**Comment by grmagalhaes** [comment]
I implemented multilevel dropdown using this excellent component as base. 

![multilevel](https://user-images.githubusercontent.com/31021721/114809495-abe1aa80-9d80-11eb-8201-abfa9c6c77f1.jpg)

**Comment by bharatribadiya** [comment]
Can you share the code?

**Comment by grmagalhaes** [comment]
You can see in my repository

Em qui, 15 de abr de 2021 00:33, bharatribadiya ***@***.***>
escreveu:
