### ISSUE TITLE
Sidebar menu drop down open

### ISSUE THREAD

**Issue by AungMy0** [azouaoui-med/pro-sidebar-template#29]
Hi Sir, 

I want to auto-open the Sidebar-dropdown if one of the submenus is selected? I have already tried to like   "" li class="sidebar-dropdown active" . It changes the color of the text but the dropdown did not open. how should I do? Thanks

**Comment by bharatribadiya** [comment]
add class active to sidebar-dropdown  and add style="display:block;" to that .sidebar-submenu
