### ISSUE TITLE
When open website sidebar is toggled

### ISSUE THREAD

**Issue by mralperem** [azouaoui-med/pro-sidebar-template#33]
Hello when i open the website the sidebar opens as it is toggled. How can i change that. What i want is to open as pinned on desktop and no toggled on mobile

**Comment by bharatribadiya** [comment]
Add class **`.pinned`** to **`.page-wrapper`** and for mobile devices remove class **`.toggled`** & **`.pinned`** by using jquery .

**Comment by mralperem** [comment]
Thank you
