### ISSUE TITLE
Load pinned and hover

### ISSUE THREAD

**Issue by samall76** [azouaoui-med/pro-sidebar-template#35]
I'm trying to use the sidebar, but I have an issue loading it in the right way. 
I want to display it as pinned and on mouseover hovered. 

My page-wrapper looks like:
```
<div class="page-wrapper default-theme sidebar-bg bg1 toggled pinned"> 
....
</div>
```
To activated the sidebar I have to click on the "Toggle Sidebar" button. So when I click on the little pinned sidebar icons not happens. 

So you can kinda see that I'm hovering over the green icon. Nothing happens.
<img width="367" alt="Screenshot 2020-05-14 at 17 30 04" src="https://user-images.githubusercontent.com/45182670/81953955-8e541000-9608-11ea-8f48-59d3cbadd763.png">

**Comment by azouaoui-med** [comment]
Is this issue occurs on mobile or desktop?

**Comment by GRINX** [comment]
Same here.. Only tested on desktop.
