### ISSUE TITLE
pro sidebar toggle

### ISSUE THREAD

**Issue by zerg052689** [azouaoui-med/pro-sidebar-template#4]
I added this 2 code in custom.js: 

 $("#toggle-sidebar").click(function () {
        $(".page-wrapper").toggleClass("toggled");
        if ($(".page-wrapper").hasClass("toggled")){
            localStorage.setItem("toggled", "true");
        }else{
            localStorage.setItem("toggled", "false");
        } 

if (localStorage.getItem("toggled") == "true"){
        $(".page-wrapper").addClass("toggled");
    }else if (localStorage.getItem("toggled") == "false"){
        $(".page-wrapper").removeClass("toggled");
    }
    });

but in console at local storage is empty , i dont see any change and sidebar not saved opened or closed ... i think need to save this in coockies or you can help me with correct code for this sidebar , i see in js code is #toggle-sidebar  but in html code from index is #close-sidebar ID , i try all posibility but not function, after refresh all changes is removed and not saved ... can you update this theme with  these function? thanks very much!

**Comment by azouaoui-med** [comment]
Create a local storage variable and save the state of the sidebar on toggle:

in custom.js you find two click events, one shows the sidebar and the other hides it
for each event you need to save the state of the sidebar whether its shown or hidden 

In the code bellow, the local storage variable is named "toggeled", and it will set to true if when shown and false if hidden
```
//show sidebar
    $("#show-sidebar").click(function () {
        $(".page-wrapper").addClass("toggled");
        localStorage.setItem("toggled", "true");
    });

 // close sidebar 
    $("#close-sidebar").click(function () {
        $(".page-wrapper").removeClass("toggled");
        localStorage.setItem("toggled", "false");
    });
```

And when page load you need to check the state of the sidebar by retrieving the value of the local storage "toggled"  and add or remove the class **toggled** from the ".page-wrapper"

```
if (localStorage.getItem("toggled") == "true") {
        $(".page-wrapper").addClass("toggled");
    } else if (localStorage.getItem("toggled") == "false") {
        $(".page-wrapper").removeClass("toggled");
    }
```

**Comment by zerg052689** [comment]
thanks for reply, but i try all options  and no function, after refresh sidebar is show , why no update js code and reupload again ..? i like to save value in a coockies js script  .. ..

**Comment by azouaoui-med** [comment]
The code should work just fine, can you check your console for errors !

**Comment by zerg052689** [comment]
in console i dont have nothing at local storage is empty results, i say again, i try all solution but not working after refresh sidebar is opened again

**Comment by azouaoui-med** [comment]
upload your code to github ... maybe you changed something
