### ISSUE TITLE
page jumps to top when interacting with the sidebar

### ISSUE THREAD

**Issue by wibed** [azouaoui-med/pro-sidebar-template#44]
when opening the the navbar

either toggling collapsed
or removing collapsed className

the page jumps to top.

reproduce:

scroll a bit
open sidebar
expected:
the page not to jump to top

actual behaviour:
page jumps to top

example: https://codepen.io/azouaoui-med/pen/wpBadb

**Comment by mralperem** [comment]
Hello did you solve this issue

**Comment by alex01at** [comment]
replace # inside the a tag with: javascript:void(0)
And all is fine :-)
