### ISSUE TITLE
Sidebar

### ISSUE THREAD

**Issue by BautistaIza** [azouaoui-med/pro-sidebar-template#53]
Hello! I wanted to tell you about an error that I have noticed. The button to close the sidebar is not working for me. In the console I mark an error. Which is the following 

<img src="https://i.imgur.com/zgTXKyF.png">
<hr>

<h3>Sorry for the google translator<h3>

**Comment by Francesco2102** [comment]
Hi,
I need help.
By default the sidebar is set to toggled, how can I make it pinned by default?
