### ISSUE TITLE
When vertical window size is too small, main-area text scrolls on top of the header bar

### ISSUE THREAD

**Issue by SlimG** [azouaoui-med/pro-sidebar-template#58]
**Describe the bug**
Content from the main-area appear on top of the header bar when the vertical size is to small to fit the left-hand meny.

**To Reproduce**
1. Expand the site horizontally until the left-hand menu appears.
2. Reduce the vertical size of the window until a vertical scroll-bar becomes visible for the left-hand menu
3. Scroll down in the main area until the main content appears on top of the header bar.

**Expected behavior**
The content of the main area not appearing on top of the header bar.

**Screenshots**
![image](https://user-images.githubusercontent.com/50249/192875536-1331585b-867b-4343-a46b-af0435983e5a.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04 LTS
 - Browser: Google Chrome
 - Version: 100.0.4896.127

**Additional context**
Last but not least. I really love the design you've made! :)

**Comment by azouaoui-med** [comment]
The header was missing background color, fixed and published

**Comment by SlimG** [comment]
Thank you very much fixing this at lightning speed! :)
