### ISSUE TITLE
[Request] optional show icons on collapse

### ISSUE THREAD

**Issue by osc2nuke** [azouaoui-med/pro-sidebar-template#6]
Woud be a nice feature if there would be an option to keep the icons visible when "close" the menu.

kind of like: 
https://bootsnipp.com/snippets/kl2OQ

**Comment by azouaoui-med** [comment]
I was thinking about adding the possibility of having multi view options for the menu where you can choose to show the icons with the text or just the icons, of course with the possibility of hiding the whole sidebar.

**Comment by azouaoui-med** [comment]
The collapse option is now available
