### ISSUE TITLE
how to delete toggle class for small screens?

### ISSUE THREAD

**Issue by firat131** [azouaoui-med/pro-sidebar-template#7]
This sidebar is very nice, thanks, but not mobile compatible. how to delete toggle class for small screens?

**Comment by azouaoui-med** [comment]
The sidebar should work just fine in mobile device ... if you can provide more details about the problem you got it will be helpful to understand the issue. 
**Note**: the sidebar position changes in small screen from `absolute` to `fixed`, to make it overlap on the **page-content** elements

**Comment by firat131** [comment]
![1](https://user-images.githubusercontent.com/43938056/46614959-c12a4e00-cb1f-11e8-823b-2267d1ac8855.PNG)
Image1: Desktop screen, no problem.
![2](https://user-images.githubusercontent.com/43938056/46614960-c1c2e480-cb1f-11e8-97d9-0a9e0028b905.PNG)
But image2: Mobile screen, sidebar does not close automatically. I want the sidebar to shut down automatically when the screen shrinks as I did in bootstrap. as follows (picture 3)
![3](https://user-images.githubusercontent.com/43938056/46614961-c1c2e480-cb1f-11e8-96a5-40abf2bee7b0.PNG)

**Comment by firat131** [comment]
Thank you very much for your quick response and help.
